$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1406457433208.9),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"94024b10d4b34224a4b4899622884074",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
        "fontName":"微软雅黑"},
      "b":{
},
      "c":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4538fa4a46b0487984e2040350469958",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":0,
              "y":20},
            "size":{
              "width":1024,
              "height":800},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
            "a":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "size":{
                "width":1200,
                "height":800}},
            "b":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":0,
                "y":50},
              "size":{
                "width":770,
                "height":880}},
            "c":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "size":{
                "width":480,
                "height":1290}}},
          "objects":[{
              "id":"6eff2fc0c8c441aa820a3d9de4f799c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":20},
                "size":{
                  "width":1024,
                  "height":800},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
                "a":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "b":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "c":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"}}}],
          "images":{
            "normal~":"images/home/u0.png",
            "normal~a":"images/home/u0_a.png",
            "normal~b":"images/home/u0_b.png",
            "normal~c":"images/home/u0_c.png"}},
{
          "id":"2ca82a8014d24772a35ef1b054d5ac72",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"18px",
            "location":{
              "x":450,
              "y":157},
            "size":{
              "width":530,
              "height":144}},
          "adaptiveStyles":{
            "a":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "size":{
                "width":730,
                "height":108}},
            "b":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "size":{
                "width":290,
                "height":252}},
            "c":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":20,
                "y":662},
              "size":{
                "width":440,
                "height":180}}},
          "objects":[{
              "id":"ca7c3103dbfa422daee183d09e072e51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"18px",
                "location":{
                  "x":450,
                  "y":157},
                "size":{
                  "width":530,
                  "height":144}},
              "adaptiveStyles":{
                "a":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "b":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "c":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif",
            "normal~c":"resources/images/transparent.gif"}},
{
          "id":"5fe452dd568b4633956aad5f5ded3201",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":96},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
            "a":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "size":{
                "width":129,
                "height":41}},
            "b":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal"},
            "c":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":20,
                "y":600}}},
          "objects":[{
              "id":"056663bb068f41eeb3f4903f60d3ee20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":96},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
                "a":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "b":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "c":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif",
            "normal~c":"resources/images/transparent.gif"}},
{
          "id":"1f2dfb7a24824ecdbd49ab5da4f79d9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":30,
              "y":100},
            "size":{
              "width":300,
              "height":300},
            "cornerRadiusTopLeft":"165"},
          "adaptiveStyles":{
            "a":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal"},
            "b":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal"},
            "c":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":90,
                "y":98}}},
          "objects":[{
              "id":"e7e4d18a5d5d4992a04a3d4450a99741",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":30,
                  "y":100},
                "size":{
                  "width":300,
                  "height":300},
                "cornerRadiusTopLeft":"165"},
              "adaptiveStyles":{
                "a":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "b":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "c":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"}}}],
          "images":{
            "normal~":"images/home/u6.png",
            "normal~c":"images/home/u6.png"}},
{
          "id":"83964e8059464eb39f9833e6c5cb9f4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1}}},
            "location":{
              "x":450,
              "y":404},
            "size":{
              "width":290,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":450,
                "y":357}},
            "b":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":450,
                "y":510}},
            "c":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":22,
                "y":941}}},
          "objects":[{
              "id":"f97de9d0fe3c4f6fa5abad004cf4e661",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1}}},
                "location":{
                  "x":450,
                  "y":404},
                "size":{
                  "width":290,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "b":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "c":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif",
            "mouseOver~a":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif",
            "mouseOver~b":"resources/images/transparent.gif",
            "normal~c":"resources/images/transparent.gif",
            "mouseOver~c":"resources/images/transparent.gif"}},
{
          "id":"49619c723a92422184af139ee00ebeb6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":342},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
            "a":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":450,
                "y":295},
              "size":{
                "width":65,
                "height":41}},
            "b":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":450,
                "y":448}},
            "c":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":22,
                "y":879}}},
          "objects":[{
              "id":"2fa9adcf95224885ba50ff22ae0554c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":342},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
                "a":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "b":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "c":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif",
            "normal~c":"resources/images/transparent.gif"}},
{
          "id":"26c793ee44884960890281ee708a173c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":510},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
            "a":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "size":{
                "width":65,
                "height":41}},
            "b":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":450,
                "y":615}},
            "c":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":22,
                "y":1050}}},
          "objects":[{
              "id":"3fa43640e9fc4bbc8c7d7c9d154e3237",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":510},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
                "a":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "b":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "c":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif",
            "normal~c":"resources/images/transparent.gif"}},
{
          "id":"5f25ce9b73a2463f967c10d272d0e89f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":790},
            "size":{
              "width":222,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal"},
            "b":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":18,
                "y":870}},
            "c":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "limbo":true}},
          "objects":[{
              "id":"1da5f878043d446d918125ab1780c46d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":790},
                "size":{
                  "width":222,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "b":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "c":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif",
            "normal~c":"resources/images/transparent.gif"}},
{
          "id":"4d5f15e958764e579c38dfdc2801195e",
          "label":"radio image",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":170},
            "size":{
              "width":275,
              "height":230}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
},
            "c":{
              "location":{
                "x":114,
                "y":168}}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"75d09050e84746c4ae211d66a14867b9",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"2d27fd32f0384f689bd26af4f28339b9",
                  "label":"",
                  "parentDynamicPanel":"4d5f15e958764e579c38dfdc2801195e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":250,
                      "height":160}},
                  "adaptiveStyles":{
                    "a":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal"},
                    "b":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal"},
                    "c":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal"}},
                  "objects":[{
                      "id":"4451c940f95d4eeaa5e08061e198f085",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4d5f15e958764e579c38dfdc2801195e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":250,
                          "height":160}},
                      "adaptiveStyles":{
                        "a":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"},
                        "b":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"},
                        "c":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"}}}],
                  "interactionMap":{
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set radio image to State2 slide up out 500ms slide up in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["4d5f15e958764e579c38dfdc2801195e"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"slideUp",
                                        "duration":500},
                                      "animateIn":{
                                        "easing":"slideUp",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "images":{
                    "normal~":"images/home/u17.jpg"}}]},
{
              "id":"924a9667ede04e27b5eb3e5d58502583",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"05b8bca9bad44cfe96fa7ffba12e9e33",
                  "label":"",
                  "parentDynamicPanel":"4d5f15e958764e579c38dfdc2801195e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":12,
                      "y":9},
                    "size":{
                      "width":230,
                      "height":112}},
                  "adaptiveStyles":{
                    "a":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal"},
                    "b":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal"},
                    "c":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal"}},
                  "objects":[{
                      "id":"8e107d48f7ba466885a7cd8273c845cc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4d5f15e958764e579c38dfdc2801195e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":12,
                          "y":9},
                        "size":{
                          "width":230,
                          "height":112}},
                      "adaptiveStyles":{
                        "a":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"},
                        "b":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"},
                        "c":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"}}}],
                  "interactionMap":{
                    "onMouseOut":{
                      "description":"OnMouseOut",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set radio image to State1 slide down out 500ms slide down in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["4d5f15e958764e579c38dfdc2801195e"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"slideDown",
                                        "duration":500},
                                      "animateIn":{
                                        "easing":"slideDown",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"dc6eb9c73cb441efa1ad7a3607b8aaa5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Corbel Regular', 'Corbel'",
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "location":{
              "x":30,
              "y":414},
            "size":{
              "width":300,
              "height":140}},
          "adaptiveStyles":{
            "a":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal"},
            "b":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal"},
            "c":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":90,
                "y":412}}},
          "objects":[{
              "id":"f3554d29470b45e7a1d700024ca45689",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Corbel Regular', 'Corbel'",
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "location":{
                  "x":30,
                  "y":414},
                "size":{
                  "width":300,
                  "height":140}},
              "adaptiveStyles":{
                "a":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "b":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "c":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~c":"resources/images/transparent.gif"}},
{
          "id":"0c5887c9f0784ee2a120b8788f9c8309",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF1A1D2C},
            "size":{
              "width":1024,
              "height":60}},
          "adaptiveStyles":{
            "a":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "size":{
                "width":1200,
                "height":60}},
            "b":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "size":{
                "width":770,
                "height":60}},
            "c":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "size":{
                "width":480,
                "height":60}}},
          "objects":[{
              "id":"0d888862f30a4b239d8770c177470721",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1A1D2C},
                "size":{
                  "width":1024,
                  "height":60}},
              "adaptiveStyles":{
                "a":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "b":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "c":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"}}}],
          "images":{
            "normal~":"images/home/u23.png",
            "normal~a":"images/home/u23_a.png",
            "normal~b":"images/home/u23_b.png",
            "normal~c":"images/home/u23_c.png"}},
{
          "id":"f29d33f1af674263a81185d361ab0c0e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":956,
              "y":6},
            "size":{
              "width":59,
              "height":51},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
            "a":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":1132,
                "y":6}},
            "b":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":701,
                "y":6}},
            "c":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":410,
                "y":6}}},
          "objects":[{
              "id":"aad40d5ad1da49fb9e015cead2c20f35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":956,
                  "y":6},
                "size":{
                  "width":59,
                  "height":51},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
                "a":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "b":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "c":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"}}}],
          "images":{
            "normal~":"images/home/u25.png",
            "normal~a":"images/home/u25.png",
            "normal~b":"images/home/u25.png",
            "normal~c":"images/home/u25.png"}},
{
          "id":"17b3b63e731440cb8ed74d1041b0b88d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Corbel Bold', 'Corbel'",
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFC0000,
              "opacity":1},
            "location":{
              "x":15,
              "y":9},
            "size":{
              "width":415,
              "height":51},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFC0000}},
          "adaptiveStyles":{
            "a":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "size":{
                "width":835,
                "height":47}},
            "b":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "size":{
                "width":686,
                "height":60}},
            "c":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "size":{
                "width":395,
                "height":60}}},
          "objects":[{
              "id":"ec03ad1ee1624fff9812e128bf8e7334",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Corbel Bold', 'Corbel'",
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFC0000,
                  "opacity":1},
                "location":{
                  "x":15,
                  "y":9},
                "size":{
                  "width":415,
                  "height":51},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFC0000}},
              "adaptiveStyles":{
                "a":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "b":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "c":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"}}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif",
            "normal~c":"resources/images/transparent.gif"}},
{
          "id":"702ed4ae524c4b0488df015b4c214aa1",
          "label":"剧照",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":338,
              "y":567},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "location":{
                "x":338,
                "y":672}},
            "c":{
              "location":{
                "x":-85,
                "y":1107}}},
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show button fade 100 ms",
                      "objectsToFades":[{
                          "objectPath":["60677a87d5e642a8b9f672a9410027dc"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"fade",
                              "duration":100,
                              "showType":"none"}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"9a53b9df634f44f980b51bf4e9ad4abf",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f625171b09e54493b081cb631439177b",
                  "label":"",
                  "parentDynamicPanel":"702ed4ae524c4b0488df015b4c214aa1",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":439,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":150},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
                    "a":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal"},
                    "b":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal"},
                    "c":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal"}},
                  "objects":[{
                      "id":"b995176f16b44534baab2b3565a0b6e9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"702ed4ae524c4b0488df015b4c214aa1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":439,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":150},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
                        "a":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"},
                        "b":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"},
                        "c":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"}}}],
                  "images":{
                    "normal~":"images/home/u30.png"}},
{
                  "id":"c8969d7a609947cc8ba53e724b184587",
                  "label":"",
                  "parentDynamicPanel":"702ed4ae524c4b0488df015b4c214aa1",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "location":{
                      "x":551,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":150},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
                    "a":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal"},
                    "b":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal",
                      "limbo":true},
                    "c":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal"}},
                  "objects":[{
                      "id":"ce21787af1804296990550ffec258cdc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"702ed4ae524c4b0488df015b4c214aa1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "location":{
                          "x":551,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":150},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
                        "a":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"},
                        "b":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"},
                        "c":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"}}}],
                  "images":{
                    "normal~":"images/home/u32.png",
                    "normal~b":"images/home/u32.png",
                    "normal~c":"images/home/u32.png"}},
{
                  "id":"65715554c64244e6a1d32e189e2ec5e8",
                  "label":"",
                  "parentDynamicPanel":"702ed4ae524c4b0488df015b4c214aa1",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":328,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":150},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
                    "a":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal"},
                    "b":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal"},
                    "c":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal"}},
                  "objects":[{
                      "id":"b7dcce78d2f342e5af09dc962a60e1bc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"702ed4ae524c4b0488df015b4c214aa1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":328,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":150},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
                        "a":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"},
                        "b":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"},
                        "c":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"}}}],
                  "images":{
                    "normal~":"images/home/u34.png"}},
{
                  "id":"63372cc813a146afafb9c1043f86397f",
                  "label":"",
                  "parentDynamicPanel":"702ed4ae524c4b0488df015b4c214aa1",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":661,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":150},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
                    "a":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal"},
                    "b":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal",
                      "limbo":true},
                    "c":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal"}},
                  "objects":[{
                      "id":"86989a4f59824837bf66cafb1c38cb21",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"702ed4ae524c4b0488df015b4c214aa1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":661,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":150},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
                        "a":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"},
                        "b":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"},
                        "c":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"}}}],
                  "images":{
                    "normal~":"images/home/u36.png",
                    "normal~b":"images/home/u36.png",
                    "normal~c":"images/home/u36.png"}},
{
                  "id":"2d70dae031704a12a7995fbc8735a63a",
                  "label":"",
                  "parentDynamicPanel":"702ed4ae524c4b0488df015b4c214aa1",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":222,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":150},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
                    "a":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal"},
                    "b":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal"},
                    "c":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal"}},
                  "objects":[{
                      "id":"cd84be33a87040d8b935d1df1032d1cd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"702ed4ae524c4b0488df015b4c214aa1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":222,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":150},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
                        "a":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"},
                        "b":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"},
                        "c":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"}}}],
                  "images":{
                    "normal~":"images/home/u38.png"}},
{
                  "id":"a97ef42e6e674b69bc14523b21e67e96",
                  "label":"",
                  "parentDynamicPanel":"702ed4ae524c4b0488df015b4c214aa1",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "mouseOver":{
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000}}},
                    "location":{
                      "x":110,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":150},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
                    "a":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal"},
                    "b":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal"},
                    "c":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal"}},
                  "objects":[{
                      "id":"6871cb7b165149cfbedb35a296405d0a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"702ed4ae524c4b0488df015b4c214aa1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "mouseOver":{
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFF0000}}},
                        "location":{
                          "x":110,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":150},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
                        "a":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"},
                        "b":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"},
                        "c":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"}}}],
                  "images":{
                    "normal~":"images/home/u40.png",
                    "mouseOver~":"images/home/u40.png"}},
{
                  "id":"f474788c11cf4d749479b9cc6e6f938e",
                  "label":"",
                  "parentDynamicPanel":"702ed4ae524c4b0488df015b4c214aa1",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "mouseOver":{
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000}}},
                    "size":{
                      "width":100,
                      "height":150},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
                    "a":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal"},
                    "b":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal"},
                    "c":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal"}},
                  "objects":[{
                      "id":"37f37c0cc8d94f7288e430102c7ce73e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"702ed4ae524c4b0488df015b4c214aa1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "mouseOver":{
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFF0000}}},
                        "size":{
                          "width":100,
                          "height":150},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
                        "a":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"},
                        "b":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"},
                        "c":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"}}}],
                  "images":{
                    "normal~":"images/home/u42.png",
                    "mouseOver~":"images/home/u42.png"}}]}]},
{
          "id":"60677a87d5e642a8b9f672a9410027dc",
          "label":"button",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":450,
              "y":600},
            "size":{
              "width":541,
              "height":90},
            "visible":false},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":648,
                "height":90}},
            "b":{
              "location":{
                "x":450,
                "y":705},
              "size":{
                "width":300,
                "height":90}},
            "c":{
              "location":{
                "x":27,
                "y":1140},
              "size":{
                "width":427,
                "height":90}}},
          "interactionMap":{
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Hide button fade 100 ms",
                      "objectsToFades":[{
                          "objectPath":["60677a87d5e642a8b9f672a9410027dc"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "easing":"fade",
                              "duration":100,
                              "showType":"none"}}}]}]}]},
            "onMouseHover":{
              "description":"OnMouseHover",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show button fade 100 ms",
                      "objectsToFades":[{
                          "objectPath":["60677a87d5e642a8b9f672a9410027dc"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"fade",
                              "duration":100,
                              "showType":"none"}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"6a6382063a494cbbbbab0ba1ef03acc6",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"60de3aec39b641cc8c47cb7820a190a7",
                  "label":"",
                  "parentDynamicPanel":"60677a87d5e642a8b9f672a9410027dc",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x7FFFFFFF},
                    "location":{
                      "x":1,
                      "y":28},
                    "size":{
                      "width":32,
                      "height":32},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000},
                    "cornerRadiusTopLeft":"16"},
                  "adaptiveStyles":{
                    "a":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal"},
                    "b":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal"},
                    "c":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal"}},
                  "objects":[{
                      "id":"e8c3ab61f4044b4286b8e8d18a7bba82",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"60677a87d5e642a8b9f672a9410027dc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x7FFFFFFF},
                        "location":{
                          "x":1,
                          "y":28},
                        "size":{
                          "width":32,
                          "height":32},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000},
                        "cornerRadiusTopLeft":"16"},
                      "adaptiveStyles":{
                        "a":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"},
                        "b":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"},
                        "c":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"}}}],
                  "images":{
                    "normal~":"images/home/u45.png"}},
{
                  "id":"a415eaf2bb1241cb855c85a224dd66c6",
                  "label":"",
                  "parentDynamicPanel":"60677a87d5e642a8b9f672a9410027dc",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x7FFFFFFF},
                    "location":{
                      "x":509,
                      "y":28},
                    "size":{
                      "width":32,
                      "height":32},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000},
                    "cornerRadiusTopLeft":"16"},
                  "adaptiveStyles":{
                    "a":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal",
                      "location":{
                        "x":617,
                        "y":28}},
                    "b":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal",
                      "location":{
                        "x":270,
                        "y":28}},
                    "c":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal",
                      "location":{
                        "x":395,
                        "y":28}}},
                  "objects":[{
                      "id":"b2dc610059c5423785187ecc4e97349e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"60677a87d5e642a8b9f672a9410027dc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x7FFFFFFF},
                        "location":{
                          "x":509,
                          "y":28},
                        "size":{
                          "width":32,
                          "height":32},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000},
                        "cornerRadiusTopLeft":"16"},
                      "adaptiveStyles":{
                        "a":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"},
                        "b":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"},
                        "c":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"}}}],
                  "images":{
                    "normal~":"images/home/u45.png",
                    "normal~a":"images/home/u45.png",
                    "normal~b":"images/home/u45.png",
                    "normal~c":"images/home/u45.png"}},
{
                  "id":"fc463a9d6c6640a4a6f11a739106d4b7",
                  "label":"",
                  "parentDynamicPanel":"60677a87d5e642a8b9f672a9410027dc",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":508,
                      "y":27},
                    "size":{
                      "width":32,
                      "height":32}},
                  "adaptiveStyles":{
                    "a":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal",
                      "location":{
                        "x":616,
                        "y":27}},
                    "b":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal",
                      "location":{
                        "x":269,
                        "y":27}},
                    "c":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal",
                      "location":{
                        "x":394,
                        "y":27}}},
                  "objects":[{
                      "id":"28452d15a87d424496a1f8ac7fb84997",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"60677a87d5e642a8b9f672a9410027dc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":508,
                          "y":27},
                        "size":{
                          "width":32,
                          "height":32}},
                      "adaptiveStyles":{
                        "a":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"},
                        "b":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"},
                        "c":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"}}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"moveWidget",
                              "description":"Move 剧照 by (110,0) swing 500ms",
                              "objectsToMoves":[{
                                  "objectPath":["702ed4ae524c4b0488df015b4c214aa1"],
                                  "moveInfo":{
                                    "moveType":"delta",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"110",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "options":{
                                      "easing":"swing",
                                      "duration":500}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u49.png",
                    "normal~a":"images/home/u49.png",
                    "normal~b":"images/home/u49.png",
                    "normal~c":"images/home/u49.png"}},
{
                  "id":"993fe5cdcb214e7eb06a19e5845fcd09",
                  "label":"",
                  "parentDynamicPanel":"60677a87d5e642a8b9f672a9410027dc",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":27},
                    "size":{
                      "width":32,
                      "height":32},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000}},
                  "adaptiveStyles":{
                    "a":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal"},
                    "b":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal"},
                    "c":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal"}},
                  "objects":[{
                      "id":"3245dfb34d1746b19a877eb39d6b93d3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"60677a87d5e642a8b9f672a9410027dc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":27},
                        "size":{
                          "width":32,
                          "height":32},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000}},
                      "adaptiveStyles":{
                        "a":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"},
                        "b":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"},
                        "c":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal"}}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"moveWidget",
                              "description":"Move 剧照 by (-110,0) swing 500ms",
                              "objectsToMoves":[{
                                  "objectPath":["702ed4ae524c4b0488df015b4c214aa1"],
                                  "moveInfo":{
                                    "moveType":"delta",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-110",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "options":{
                                      "easing":"swing",
                                      "duration":500}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u51.png"}}]}]},
{
          "id":"ef38beae88b34fcf949706572aa02382",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":996,
              "y":562},
            "size":{
              "width":114,
              "height":180},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
            "a":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":1108,
                "y":562},
              "size":{
                "width":112,
                "height":180}},
            "b":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":750,
                "y":667},
              "size":{
                "width":150,
                "height":180}},
            "c":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":465,
                "y":1102},
              "size":{
                "width":342,
                "height":180}}},
          "objects":[{
              "id":"e817ee96719f421da33c705c555dd5b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":996,
                  "y":562},
                "size":{
                  "width":114,
                  "height":180},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
                "a":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "b":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "c":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"}}}],
          "images":{
            "normal~":"images/home/u53.png",
            "normal~a":"images/home/u53_a.png",
            "normal~b":"images/home/u53_b.png",
            "normal~c":"images/home/u53_c.png"}},
{
          "id":"3c735325b5094239a021a72d4eaf2a63",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":562},
            "size":{
              "width":427,
              "height":180},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
            "a":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal"},
            "b":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":18,
                "y":667}},
            "c":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":-405,
                "y":1102}}},
          "objects":[{
              "id":"197263c55bbf4f119a9048a8a450139f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":562},
                "size":{
                  "width":427,
                  "height":180},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
                "a":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "b":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "c":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"}}}],
          "images":{
            "normal~":"images/home/u55.png",
            "normal~b":"images/home/u55.png",
            "normal~c":"images/home/u55.png"}},
{
          "id":"56c867d98038411d988a8d19012af228",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":430},
            "size":{
              "width":290,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":450,
                "y":383}},
            "b":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":450,
                "y":536}},
            "c":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":22,
                "y":967}}},
          "objects":[{
              "id":"4756226e47ef45919fc0f390ae182f1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":430},
                "size":{
                  "width":290,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "b":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "c":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif",
            "normal~c":"resources/images/transparent.gif"}},
{
          "id":"e93fc14d7c8c490698a12e77d74b2bc3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":457},
            "size":{
              "width":290,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":450,
                "y":410}},
            "b":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":450,
                "y":563}},
            "c":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":22,
                "y":994}}},
          "objects":[{
              "id":"0068148893a048faa40f55df8271532d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":457},
                "size":{
                  "width":290,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "b":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "c":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif",
            "normal~c":"resources/images/transparent.gif"}},
{
          "id":"707540ff03894db7ae778a1ffa9b1a2f",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1018,
              "y":552},
            "size":{
              "width":10,
              "height":200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":1195,
                "y":552}},
            "b":{
              "location":{
                "x":763,
                "y":657}},
            "c":{
              "location":{
                "x":475,
                "y":1092}}},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u61_line.png",
            "start~a":"resources/images/transparent.gif",
            "end~a":"resources/images/transparent.gif",
            "line~a":"images/home/u61_line.png",
            "start~a":"resources/images/transparent.gif",
            "end~a":"resources/images/transparent.gif",
            "line~a":"images/home/u61_line.png",
            "start~b":"resources/images/transparent.gif",
            "end~b":"resources/images/transparent.gif",
            "line~b":"images/home/u61_line.png",
            "start~b":"resources/images/transparent.gif",
            "end~b":"resources/images/transparent.gif",
            "line~b":"images/home/u61_line.png",
            "start~c":"resources/images/transparent.gif",
            "end~c":"resources/images/transparent.gif",
            "line~c":"images/home/u61_line.png",
            "start~c":"resources/images/transparent.gif",
            "end~c":"resources/images/transparent.gif",
            "line~c":"images/home/u61_line.png"}},
{
          "id":"1a9cacc2bec9446380a4d72f8927df3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":485,
              "y":1354},
            "size":{
              "width":222,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":485,
                "y":1354}},
            "b":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":485,
                "y":1354}},
            "c":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":22,
                "y":1297},
              "limbo":false}},
          "objects":[{
              "id":"b2551ac055e144cf8d4d94eab95ad4fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":485,
                  "y":1354},
                "size":{
                  "width":222,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "b":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "c":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif",
            "normal~c":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "4538fa4a46b0487984e2040350469958":{
      "scriptId":"u0"},
    "6eff2fc0c8c441aa820a3d9de4f799c4":{
      "scriptId":"u1"},
    "2ca82a8014d24772a35ef1b054d5ac72":{
      "scriptId":"u2"},
    "ca7c3103dbfa422daee183d09e072e51":{
      "scriptId":"u3"},
    "5fe452dd568b4633956aad5f5ded3201":{
      "scriptId":"u4"},
    "056663bb068f41eeb3f4903f60d3ee20":{
      "scriptId":"u5"},
    "1f2dfb7a24824ecdbd49ab5da4f79d9a":{
      "scriptId":"u6"},
    "e7e4d18a5d5d4992a04a3d4450a99741":{
      "scriptId":"u7"},
    "83964e8059464eb39f9833e6c5cb9f4b":{
      "scriptId":"u8"},
    "f97de9d0fe3c4f6fa5abad004cf4e661":{
      "scriptId":"u9"},
    "49619c723a92422184af139ee00ebeb6":{
      "scriptId":"u10"},
    "2fa9adcf95224885ba50ff22ae0554c3":{
      "scriptId":"u11"},
    "26c793ee44884960890281ee708a173c":{
      "scriptId":"u12"},
    "3fa43640e9fc4bbc8c7d7c9d154e3237":{
      "scriptId":"u13"},
    "5f25ce9b73a2463f967c10d272d0e89f":{
      "scriptId":"u14"},
    "1da5f878043d446d918125ab1780c46d":{
      "scriptId":"u15"},
    "4d5f15e958764e579c38dfdc2801195e":{
      "scriptId":"u16"},
    "2d27fd32f0384f689bd26af4f28339b9":{
      "scriptId":"u17"},
    "4451c940f95d4eeaa5e08061e198f085":{
      "scriptId":"u18"},
    "05b8bca9bad44cfe96fa7ffba12e9e33":{
      "scriptId":"u19"},
    "8e107d48f7ba466885a7cd8273c845cc":{
      "scriptId":"u20"},
    "dc6eb9c73cb441efa1ad7a3607b8aaa5":{
      "scriptId":"u21"},
    "f3554d29470b45e7a1d700024ca45689":{
      "scriptId":"u22"},
    "0c5887c9f0784ee2a120b8788f9c8309":{
      "scriptId":"u23"},
    "0d888862f30a4b239d8770c177470721":{
      "scriptId":"u24"},
    "f29d33f1af674263a81185d361ab0c0e":{
      "scriptId":"u25"},
    "aad40d5ad1da49fb9e015cead2c20f35":{
      "scriptId":"u26"},
    "17b3b63e731440cb8ed74d1041b0b88d":{
      "scriptId":"u27"},
    "ec03ad1ee1624fff9812e128bf8e7334":{
      "scriptId":"u28"},
    "702ed4ae524c4b0488df015b4c214aa1":{
      "scriptId":"u29"},
    "f625171b09e54493b081cb631439177b":{
      "scriptId":"u30"},
    "b995176f16b44534baab2b3565a0b6e9":{
      "scriptId":"u31"},
    "c8969d7a609947cc8ba53e724b184587":{
      "scriptId":"u32"},
    "ce21787af1804296990550ffec258cdc":{
      "scriptId":"u33"},
    "65715554c64244e6a1d32e189e2ec5e8":{
      "scriptId":"u34"},
    "b7dcce78d2f342e5af09dc962a60e1bc":{
      "scriptId":"u35"},
    "63372cc813a146afafb9c1043f86397f":{
      "scriptId":"u36"},
    "86989a4f59824837bf66cafb1c38cb21":{
      "scriptId":"u37"},
    "2d70dae031704a12a7995fbc8735a63a":{
      "scriptId":"u38"},
    "cd84be33a87040d8b935d1df1032d1cd":{
      "scriptId":"u39"},
    "a97ef42e6e674b69bc14523b21e67e96":{
      "scriptId":"u40"},
    "6871cb7b165149cfbedb35a296405d0a":{
      "scriptId":"u41"},
    "f474788c11cf4d749479b9cc6e6f938e":{
      "scriptId":"u42"},
    "37f37c0cc8d94f7288e430102c7ce73e":{
      "scriptId":"u43"},
    "60677a87d5e642a8b9f672a9410027dc":{
      "scriptId":"u44"},
    "60de3aec39b641cc8c47cb7820a190a7":{
      "scriptId":"u45"},
    "e8c3ab61f4044b4286b8e8d18a7bba82":{
      "scriptId":"u46"},
    "a415eaf2bb1241cb855c85a224dd66c6":{
      "scriptId":"u47"},
    "b2dc610059c5423785187ecc4e97349e":{
      "scriptId":"u48"},
    "fc463a9d6c6640a4a6f11a739106d4b7":{
      "scriptId":"u49"},
    "28452d15a87d424496a1f8ac7fb84997":{
      "scriptId":"u50"},
    "993fe5cdcb214e7eb06a19e5845fcd09":{
      "scriptId":"u51"},
    "3245dfb34d1746b19a877eb39d6b93d3":{
      "scriptId":"u52"},
    "ef38beae88b34fcf949706572aa02382":{
      "scriptId":"u53"},
    "e817ee96719f421da33c705c555dd5b3":{
      "scriptId":"u54"},
    "3c735325b5094239a021a72d4eaf2a63":{
      "scriptId":"u55"},
    "197263c55bbf4f119a9048a8a450139f":{
      "scriptId":"u56"},
    "56c867d98038411d988a8d19012af228":{
      "scriptId":"u57"},
    "4756226e47ef45919fc0f390ae182f1a":{
      "scriptId":"u58"},
    "e93fc14d7c8c490698a12e77d74b2bc3":{
      "scriptId":"u59"},
    "0068148893a048faa40f55df8271532d":{
      "scriptId":"u60"},
    "707540ff03894db7ae778a1ffa9b1a2f":{
      "scriptId":"u61"},
    "1a9cacc2bec9446380a4d72f8927df3f":{
      "scriptId":"u62"},
    "b2551ac055e144cf8d4d94eab95ad4fe":{
      "scriptId":"u63"}}});