$axure.loadCurrentPage({
  "url":"娜塔莉波曼.html",
  "generationDate":new Date(1406457009839.68),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b43d790991044f76b51c867b95cd1f19",
    "type":"Axure:Page",
    "name":"娜塔莉波曼",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
},
      "b":{
        "fontName":"微软雅黑"},
      "c":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5ad781c467d948638d8949d42c4d3f32",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "size":{
              "width":1024,
              "height":800},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "size":{
                "width":770,
                "height":670}},
            "c":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "size":{
                "width":480,
                "height":560}}},
          "objects":[{
              "id":"b245f4262b45425087d2c2299c5dfd9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "size":{
                  "width":1024,
                  "height":800},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
                "a":{
},
                "b":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "c":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"}}}],
          "images":{
            "normal~":"images/home/u0.png",
            "normal~b":"images/娜塔莉波曼/u0_b.png",
            "normal~c":"images/娜塔莉波曼/u0_c.png"}},
{
          "id":"ce0d416f43c24110a944a186ede83d44",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"18px",
            "location":{
              "x":30,
              "y":707},
            "size":{
              "width":950,
              "height":54}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":30,
                "y":566},
              "size":{
                "width":710,
                "height":72}},
            "c":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":20,
                "y":405},
              "size":{
                "width":440,
                "height":126}}},
          "objects":[{
              "id":"0613e676e8174016a68a024f7b9ae7b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"18px",
                "location":{
                  "x":30,
                  "y":707},
                "size":{
                  "width":950,
                  "height":54}},
              "adaptiveStyles":{
                "a":{
},
                "b":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "c":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif",
            "normal~c":"resources/images/transparent.gif"}},
{
          "id":"bcba9cce897f4b00b91f5c3d4d31b5df",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":662},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":30,
                "y":521},
              "size":{
                "width":129,
                "height":41}},
            "c":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":20,
                "y":360}}},
          "objects":[{
              "id":"b2d8613d193c4b8f8597faeec52db781",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":662},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
                "a":{
},
                "b":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "c":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif",
            "normal~c":"resources/images/transparent.gif"}},
{
          "id":"cbe9820024f04ba59f61b0f713ef444b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":100},
            "size":{
              "width":1009,
              "height":528},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "size":{
                "width":742,
                "height":389}},
            "c":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "size":{
                "width":458,
                "height":240}}},
          "objects":[{
              "id":"dbdb92fad2d745f5a47dd84cc747ac6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":100},
                "size":{
                  "width":1009,
                  "height":528},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
                "a":{
},
                "b":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"},
                "c":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal"}}}],
          "images":{
            "normal~":"images/娜塔莉波曼/u6.png",
            "normal~b":"images/娜塔莉波曼/u6.png",
            "normal~c":"images/娜塔莉波曼/u6.png"}},
{
          "id":"0c62b13965bc4c218064318e45b302c8",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
            "a":{
},
            "b":{
},
            "c":{
}},
          "masterId":"956c367a985e466787b4df3d7367ffda"}]}},
  "masters":{
    "956c367a985e466787b4df3d7367ffda":{
      "packageId":"956c367a985e466787b4df3d7367ffda",
      "type":"Axure:Master",
      "name":"head",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
},
        "b":{
},
        "c":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"2235e535e1714b51a79688be7930130d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF1A1D2C},
              "size":{
                "width":1024,
                "height":60}},
            "adaptiveStyles":{
              "a":{
                "size":{
                  "width":1200,
                  "height":60}},
              "b":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "size":{
                  "width":770,
                  "height":60}},
              "c":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "size":{
                  "width":480,
                  "height":60}}},
            "objects":[{
                "id":"5325566b03bb43dd813b49edf7c049d4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF1A1D2C},
                  "size":{
                    "width":1024,
                    "height":60}},
                "adaptiveStyles":{
                  "a":{
},
                  "b":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontWeight":"400",
                    "fontStyle":"normal"},
                  "c":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontWeight":"400",
                    "fontStyle":"normal"}}}],
            "images":{
              "normal~":"images/home/u23.png",
              "normal~a":"images/home/u23_a.png",
              "normal~b":"images/home/u23_b.png",
              "normal~c":"images/home/u23_c.png"}},
{
            "id":"3b3d7752ad7649358931c56337e43686",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":956,
                "y":6},
              "size":{
                "width":59,
                "height":51},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":1132,
                  "y":6}},
              "b":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":701,
                  "y":6}},
              "c":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":410,
                  "y":6}}},
            "objects":[{
                "id":"00fe660890a14989acad43ad4885612b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":956,
                    "y":6},
                  "size":{
                    "width":59,
                    "height":51},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
                  "a":{
},
                  "b":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontWeight":"400",
                    "fontStyle":"normal"},
                  "c":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontWeight":"400",
                    "fontStyle":"normal"}}}],
            "images":{
              "normal~":"images/home/u25.png",
              "normal~a":"images/home/u25.png",
              "normal~b":"images/home/u25.png",
              "normal~c":"images/home/u25.png"}},
{
            "id":"85c76aaa18564d08bf3e9324468b7c8b",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Corbel Bold', 'Corbel'",
              "fontSize":"36px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFC0000,
                "opacity":1},
              "location":{
                "x":15,
                "y":10},
              "size":{
                "width":415,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFC0000}},
            "adaptiveStyles":{
              "a":{
                "size":{
                  "width":835,
                  "height":47}},
              "b":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "size":{
                  "width":686,
                  "height":60}},
              "c":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "size":{
                  "width":395,
                  "height":60}}},
            "objects":[{
                "id":"7e9de543159c4da5bfe63b0a6b2a611c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Corbel Bold', 'Corbel'",
                  "fontSize":"36px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFC0000,
                    "opacity":1},
                  "location":{
                    "x":15,
                    "y":10},
                  "size":{
                    "width":415,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFC0000}},
                "adaptiveStyles":{
                  "a":{
},
                  "b":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontWeight":"400",
                    "fontStyle":"normal"},
                  "c":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontWeight":"400",
                    "fontStyle":"normal"}}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~a":"resources/images/transparent.gif",
              "normal~b":"resources/images/transparent.gif",
              "normal~c":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "5ad781c467d948638d8949d42c4d3f32":{
      "scriptId":"u0"},
    "b245f4262b45425087d2c2299c5dfd9c":{
      "scriptId":"u1"},
    "ce0d416f43c24110a944a186ede83d44":{
      "scriptId":"u2"},
    "0613e676e8174016a68a024f7b9ae7b4":{
      "scriptId":"u3"},
    "bcba9cce897f4b00b91f5c3d4d31b5df":{
      "scriptId":"u4"},
    "b2d8613d193c4b8f8597faeec52db781":{
      "scriptId":"u5"},
    "cbe9820024f04ba59f61b0f713ef444b":{
      "scriptId":"u6"},
    "dbdb92fad2d745f5a47dd84cc747ac6e":{
      "scriptId":"u7"},
    "0c62b13965bc4c218064318e45b302c8":{
      "scriptId":"u8",
      "2235e535e1714b51a79688be7930130d":{
        "scriptId":"u9"},
      "5325566b03bb43dd813b49edf7c049d4":{
        "scriptId":"u10"},
      "3b3d7752ad7649358931c56337e43686":{
        "scriptId":"u11"},
      "00fe660890a14989acad43ad4885612b":{
        "scriptId":"u12"},
      "85c76aaa18564d08bf3e9324468b7c8b":{
        "scriptId":"u13"},
      "7e9de543159c4da5bfe63b0a6b2a611c":{
        "scriptId":"u14"}}}});